### PR TITLE
Added vertical functionality and relevant sample.

### PR DESCRIPTION
**Pull request by ZiroDiv**
TODO: Rename some variables. Also maybe merge vertical and horizontal views to a single widget

I have seen that there is a vertical branch already but I am not sure about it's progress

### CODE REVIEW

**Comment by shchurov** [comment]
@ZiroDiv, hi there!
I'm not sure if there's a vertical branch somewhere so your contribution is very valuable, thanks! I will try to check it tomorrow.

**Comment by shchurov** [comment]
@ZiroDiv, I took a glance at the PR, looks good!
May I ask you to allow changes to your branch, so I can do some minor styling changes before merging it? You can read how to do that here: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by ZiroDiv** [comment]
Hello Mykhailo,
I am kind of new in both git and github and this was my first pull request so I am kind of lost sometimes.
I checked the instructions and the Allow edits from maintainers is checked for this commit. Can't figure out what is missing.

Thanks

**Comment by ZiroDiv** [comment]
Hello Mykhailo,
I am kind of new in both git and github and this was my first pull request so I am kind of lost sometimes.
I checked the instructions and the Allow edits from maintainers is checked for this commit. Can't figure out what is missing.

Thanks

**Comment by shchurov** [comment]
@ZiroDiv, ok cool, just to be sure that it's enabled. Will check it on Monday.

**Comment by shchurov** [comment]
@ZiroDiv, I had time to check it again today. And I have a strong feeling that this `VerticalWheelView` should be forked as a separate library and here's why:

- besides switching `y` to `x` and `height` to `width` it also requires to do the same thing to all the paddings (e.g. `getPaddingTop()` to `getPaddingLeft()`)
- a lot of checks through the code `if (horizontal) ... else ...` which is a good indicator of need for replacing conditional with polymorphism. And in general breaking class hierarchy to something like `WheelView` as an abstract parent with `HorizontalWheelView` and `VerticalWheelView` as children would be an optimal solution. But because the library originally supports only horizontal orientation (_HorizontalWheelView_) and demand for vertical orientation is significantly lower I think it would be a wrong design decision. Also in some way it's _Interface segregation principle_ in action, I would prefer to have a few specific libraries than one that does everything.

My suggestion is that you could make a separate fork that replaces horizontal orientation with vertical. Then I would put a link to it in `HorizontalWheelView` readme.

Besides that I have a couple of suggestions for improving code in the PR:

- as I said all paddings should also be replaced (top to left, bottom to right etc.)
- [This check](https://github.com/ZiroDiv/HorizontalWheelView/blob/master/library/src/main/java/com/github/shchurov/horizontalwheelview/HorizontalWheelView.java#L75) brings some inconsistency, for instance at 360 degree `onRotationChanged` will or will not be called depending on `endLock` value
- [Here](https://github.com/ZiroDiv/HorizontalWheelView/blob/master/library/src/main/java/com/github/shchurov/horizontalwheelview/Drawer.java#L44), I think the general convention is to use `is` prefix in boolean getters and not use it in variable names, for instance `boolean readable = true` and `boolean isReadable() {..}`

**Comment by ZiroDiv** [comment]
@shchurov thanks a lot for the review and comments. I agree with most of them, I also wanted to suggest having an parent WheelView (ideally not abstract) but it is indeed a big redesign if there is no demand. 

I do not really like the idea of having two libraries for many reasons. It violates the code re usability rule especially if someone needs both of them on the same project. 

I thought that the padding was working okay on the example - I will recheck.

I added the check because I was getting a deadlock when the one wheel was changing the value of the second and back. Often you can get big performance boost with such checks.

For now I will keep these changes on a fork and compromise on some design drawback due to the very small effort of the changes. We can see if it worth making a wheel view library because a simple alternative could be using the vertical wheel and rotating by 90 or 270 degrees on the GUI

**PS** - Can you please let me know how I can add the links to the code? Didn't knew this feature of markdown.

**Comment by shchurov** [comment]
@ZiroDiv, that is my main doubt, it will require relatively big refactoring and significant effort to support while it's not a very demanded feature. 

I think the paddings still work because only bottomPadding is set in the sample app.
Although haven't tried to rotate it using `setRotation`, I'm not sure if it will be layout correctly.

> Can you please let me know how I can add the links to the code? Didn't knew this feature of markdown.

Absolutely, just click on a line number and it will build a link to that line

**Pull request closed without merging**
